apiVersion: v1
kind: Namespace
metadata:
  name: codereview
  labels:
    name: codereview
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: codereview-monitoring
  labels:
    name: codereview-monitoring
    environment: production
